[RFC][mono] Add suport for denied assemblies, fixed bxc#56682
mono/msbuild pull request #23
Opened 2017-08-02 19:33 UTC by radical

Mono denies loading certain "bad" assemblies because they include an
implementation that doesn't work under mono. Instead, mono provides it's
own implementations of the same which are safe to load.

These are specific versions from specific nugets. Mono installs a list
of these in $(MSBuildExtensionsPath)/deniedAssemblyList.txt .

If these bad assemblies get bundled with an app and the runtime tries to
load them, then they will get denied. If this is running from a full
mono installation, then the runtime continues looking for the assembly
in other locations.

But if this is a case, like a Mac app bundle (with Xamarin.Mac), which
uses it's own bundled mono+assemblies, then the runtime won't be able to
fallback to anything else. So, we want to ensure that we bundle the
"good" assemblies instead.

We are doing that by filtering out such references (`@(Reference)`) before
the `ResolveAssemblyReference` task. All the facades are being
referenced, so the correct assemblies will get pulled in accordingly.

For this, we add a `FilterDeniedAssemblies` tasks in a new
`Mono.Build.Tasks.dll`.

Note: the list is part of this commit for now. Before the merge, this
will be generated+installed from mono instead.

Fix: https://bugzilla.xamarin.com/show_bug.cgi?id=56682

2017-08-02 19:36 UTC, radical commented
This is not the final thing! The list of denied assembly is assumed to have been installed by mono in `lib/mono/xbuild`. Since, mono doesn't do that yet, the file is bundled in the commit and copied by hand.

Note: the list is part of this commit for now. Before the merge, this will be generated+installed from mono instead.

2017-08-02 20:18 UTC, radical commented
Oh and this needs *testing*!! :)

2017-08-03 07:26 UTC, marek-safar commented on mono/tasks/FilterDeniedAssemblies.cs
> +            var id = guid.ToString ().ToUpper  ();
Should be ToUpperInvariant and ToString with culture.invariantculture

2017-08-03 16:57 UTC, chamons approved these changes
I'd love a test (maybe in xamarin-macios) for this somewhere.

2017-08-03 16:57 UTC, chamons commented on mono/ExtensionsPath-ToolsVersion/Microsoft.Common.targets/ImportAfter/Microsoft.Common.Mono.After.targets
> +        <Message Text="Removed references to assemblies that are denied loading by Mono runtime: %(DeniedReferences.DeniedAssemblyPath)" Importance="Low" />
As a user, I have no clue what this means. Either we should remove the message, have it do something like I did in the IDE:

```DebuggerLoggingService.LogAndShowException ("Unable to launch application to debug, possibly due to it crashing quickly.\nSee https://aka.ms/xm-crash-no-output for more help.", e);```

or rephrase it to something like:

"Ignoring references to assembles {} as they are denied loading by Mono runtime". That way it is at least clear that we saw them and are doing nothing, vs remove, which suggests change (did they change my project? do I need to do anything?).

2017-08-03 16:57 UTC, chamons commented on mono/tasks/FilterDeniedAssemblies.cs
> +            Log.LogMessage(MessageImportance.Low, "No list of denied assemblies was found, so not filtering any references.");
Is this something a user should see? I'd suggest either direct them to file a bug at bugzilla.xamarin.com/index.cgi or make it debug only?

2017-08-03 16:57 UTC, chamons commented on mono/tasks/FilterDeniedAssemblies.cs
> +            ver = entry.Version;
Can metadataReader.GetAssemblyDefinition() ever return null?

2017-08-03 17:14 UTC, radical commented on mono/tasks/FilterDeniedAssemblies.cs
> +            Log.LogMessage(MessageImportance.Low, "No list of denied assemblies was found, so not filtering any references.");
This would be seen only in a detailed or diagnostic log. Suggesting them to file a bug sounds like a good idea.

2017-08-03 17:15 UTC, radical commented on mono/tasks/FilterDeniedAssemblies.cs
> +            ver = entry.Version;
The documentation wasn't very helpful. Source we'll have a non-null value or an exception. https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/src/System/Reflection/Metadata/MetadataReader.cs#L1048-L1055

2017-08-03 17:16 UTC, chamons commented on mono/tasks/FilterDeniedAssemblies.cs
> +            Log.LogMessage(MessageImportance.Low, "No list of denied assemblies was found, so not filtering any references.");
We have some messages like that in mmp:

https://github.com/xamarin/xamarin-macios/blob/master/tools/mmp/driver.cs#L846

2017-08-03 17:18 UTC, radical commented on mono/ExtensionsPath-ToolsVersion/Microsoft.Common.targets/ImportAfter/Microsoft.Common.Mono.After.targets
> +        <Message Text="Removed references to assemblies that are denied loading by Mono runtime: %(DeniedReferences.DeniedAssemblyPath)" Importance="Low" />
Sure, your message makes sense. This is also a detailed/diagnostic message, and completely normal, doesn't indicate any issues, so I don't see why it should be surfaced in the IDE. Feel free to correct me of course :)

2017-08-03 17:19 UTC, radical commented
re:test, oh, I am not declaring this done yet! I will create a wrench lane to get a build for this and then you can test it. I tried it basically with your `TestRoslynApp` sample and one other project, essentially.

2017-08-03 17:20 UTC, radical commented
re:test, um but yeah, we should be adding a test for this, XM is a good place for it.

2017-08-05 00:51 UTC, radical commented
Updated with a different approach.

2017-08-07 17:15 UTC, chamons commented on install-mono-prefix.sh
> +mv ${MSBUILD_OUT_DIR}/Mono.Build.Tasks.* ${DESTDIR}${XBUILD_DIR}
Should this be copy?

2017-08-07 17:16 UTC, chamons commented on mono/tasks/FilterDeniedAssemblies.cs
> +        static string s_deniedListFilename = "deniedAssembliesList.txt";
I've not seeing type prefixes in variables names before? Is this an msbuild ism?

2017-08-07 17:23 UTC, radical commented on mono/tasks/FilterDeniedAssemblies.cs
> +        static string s_deniedListFilename = "deniedAssembliesList.txt";
This is just for *static* fields, and yeah it's a msbuild code style (which made things a little easier to read here too!). The source file has a mixed mono and msbuild style though, which I should clean up too!

2017-08-07 17:28 UTC, radical commented on install-mono-prefix.sh
> +mv ${MSBUILD_OUT_DIR}/Mono.Build.Tasks.* ${DESTDIR}${XBUILD_DIR}
Yeah :)

2017-08-07 17:34 UTC, chamons commented on mono/tasks/FilterDeniedAssemblies.cs
> +        {
Not to place C# golf but...


```		static string Stringify (List<string> list)
		{
			var spaceSeperated = String.Join (", ", list);
			if (list.Count > 1)
				spaceSeperated = spaceSeperated.Insert (spaceSeperated.LastIndexOf (',') + 1, " and");
			return spaceSeperated;
		}```

2017-08-08 21:35 UTC, radical commented
Updated to reflect @chamons' suggested changes.

2017-08-11 19:37 UTC, akoeplinger requested changes

2017-08-11 19:37 UTC, akoeplinger commented on mono/ExtensionsPath-ToolsVersion/Microsoft.Common.targets/ImportAfter/Microsoft.Common.Mono.After.targets
> +Microsoft.Common.Mono.targets
should be `Microsoft.Common.Mono.After.targets` to match the file name.

2017-08-11 19:37 UTC, akoeplinger commented on mono/tasks/FilterDeniedAssemblies.cs
> +            } catch (FileNotFoundException fe) when (fe.FileName != null && String.Compare(Path.GetFileName(fe.FileName), s_deniedListFilename) == 0) {
I've been told by Zoltan that exception filter clauses should be avoided if possible. Is there a reason why we need to catch FileNotFoundException instead of simply doing `if (!File.Exists())`?

2017-08-11 19:37 UTC, akoeplinger commented on mono/tasks/FilterDeniedAssemblies.cs
> +                                        " Please file a bug report at http://bugzilla.xamarin.com .");
https please

2017-08-11 19:37 UTC, akoeplinger commented on mono/tasks/FilterDeniedAssemblies.cs
> +                    Log.LogWarning(null, "MSB3911", null, null, -1, -1, -1, -1, $"INTERNAL WARNING: {fe.Message}. Please file a bug report at http://bugzilla.xamarin.com .");
https please

2017-08-11 19:37 UTC, akoeplinger commented on mono/tasks/FilterDeniedAssemblies.cs
> +            if (strings?.Length == 0)
this won't catch a null `strings` and make String.Join() crash later on.

2017-08-11 19:37 UTC, akoeplinger commented on mono/tasks/FilterDeniedAssemblies.cs
> +                commaSeparatedString = commaSeparatedString.Insert(commaSeparatedString.IndexOf(",") + 1, " and");
this would print `"abc, def, and foo"` (note comma before `and`).

What about:

```csharp
if (strings.Length == 1)
   return strings[0];

var allButLast = new ArraySegment<string>(strings, 0, strings.Length-1);
return String.Join(",", allButLast) + " and " + strings[strings.Length-1];
```

Though I wonder whether we need to get this fancy at all in a simple warning message? I think a simple `String.Join(",", strings)` should do it as well.

2017-08-11 19:40 UTC, radical commented on mono/tasks/FilterDeniedAssemblies.cs
> +                commaSeparatedString = commaSeparatedString.Insert(commaSeparatedString.IndexOf(",") + 1, " and");
I have an updated patch which I haven't pushed yet. And that removes this method as I am not including the list of search paths in the user-visible warning. It didn't seem to have any value for a user. It would be useful only for somebody debugging, who will get the list in a diagnostic log.

2017-08-11 19:41 UTC, radical commented on mono/tasks/FilterDeniedAssemblies.cs
> +            } catch (FileNotFoundException fe) when (fe.FileName != null && String.Compare(Path.GetFileName(fe.FileName), s_deniedListFilename) == 0) {
Does it not work well on mono? I can rework to avoid it.

2017-08-11 19:45 UTC, radical commented on mono/tasks/FilterDeniedAssemblies.cs
> +            if (strings?.Length == 0)
yikes! thanks!

2017-08-11 19:47 UTC, akoeplinger commented on mono/tasks/FilterDeniedAssemblies.cs
> +            } catch (FileNotFoundException fe) when (fe.FileName != null && String.Compare(Path.GetFileName(fe.FileName), s_deniedListFilename) == 0) {
Apparently it has some issues, can't remember the exact details. Better to rework it if it's easy :)

2017-08-11 21:21 UTC, radical commented
Updated. Hopefully, this is ready this time :) Added a test project too.

2017-08-11 22:02 UTC, radical commented
Updated again: made this an opt-in feature, via `$(FilterDeniedAssemblies)`, just to reduce the impact of this. We can enable this in XM for now. And any other profile owners that we might have, can do the same.

2017-08-12 00:33 UTC, akoeplinger approved these changes

2017-08-15 07:32 UTC, borgdylan commented
Will the latest SDK bits be added as well? At present NETStandard 2.0 support is completely missing.

2017-08-15 13:48 UTC, chamons commented
@borgdylan https://gitter.im/xamarin/xamarin-macios (or the other associated channels) is a more appropriate location for such questions.

Though if you are asking about Xamarin.Mac or iOS - https://medium.com/@donblas/xamarin-mac-and-netstandard2-708a06890302

2017-08-15 14:36 UTC, borgdylan commented
I had asked under the msbuild gitter (was asking about mono msbuild fork) and got no response.

2017-08-16 03:32 UTC, merged