Automate process for updating SDKs
mono/msbuild pull request #39
Opened 2018-02-07 11:03 UTC by radical

2018-02-14 18:03 UTC, radical commented
@akoeplinger @marek-safar Could you please review this too?

2018-02-15 13:58 UTC, marek-safar requested changes
Please add documentation how it this supposed to be used and updated

2018-03-01 08:53 UTC, radical commented
Added the documentation.

2018-03-01 14:27 UTC, marek-safar approved these changes

2018-03-01 14:40 UTC, akoeplinger reviewed
I think it's ok but I'm a little concerned how we'll ensure we're shipping the right set of files given how much hardcoded logic is in these msbuild targets.

2018-03-01 14:40 UTC, akoeplinger commented on mono/build/sdks_and_nugets/update_nuget_build_tasks.proj
> +        <Exec Command="find $(TmpPackageDirectory) -type f -iwholename '*net4[567]*' -a ! -name _._ -exec cp {} $(NuGetExtensionsPath) &quot;;&quot;" />
not sure what the goal here is but the regex won't work for e.g. `net471` or `net48`

2018-03-01 14:40 UTC, akoeplinger commented on mono/build/sdks_and_nugets/update_nuget_build_tasks.proj
> +        <Exec Command="find $(NuGetExtensionsPathToolsVersion) -type f -exec chmod -x {} &quot;;&quot;" />
do we really need to chmod _all_ files?

2018-03-01 19:50 UTC, radical commented on mono/build/sdks_and_nugets/update_nuget_build_tasks.proj
> +        <Exec Command="find $(NuGetExtensionsPathToolsVersion) -type f -exec chmod -x {} &quot;;&quot;" />
We don't need exec bit on any of the files! And ya, all of them seem to end up with that bit set. This is converted from the bash scripts that I had and will be improved as I use them more. Adding to the repo ensures that they won't be lost and can be maintained better.

2018-03-01 19:50 UTC, radical commented
@akoeplinger this basically a collection of all the steps that I need to take to update the SDKs. And then it is followed by checking `git status` to see what was deleted or look for any new files that might need to be added. And then install+test. So, this isn't really meant as a 100% automated process. It just makes this part of it, which is repetitive a bit quicker. If things change upstream, like nugets get added/removed, or layouts change then that has to be reflected here. But given that this kinda update needs to be done pretty frequently, the scripts help with that. I will make them better as I use them, but you are correct that they are very dependent on what upstream does. And any changes there will have to be tracked here.

2018-03-01 19:53 UTC, akoeplinger approved these changes

2018-03-01 19:56 UTC, merged